<section id="main-content">
  <div class="row">
    <div class="large-12 columns">
      <h1>Foundation Icon Fonts 3</h1> 

      <h2>General Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="heart"><i class="fi-heart"></i> heart</li>
        <li class="star"><i class="fi-star"></i> star</li>
        <li class="plus"><i class="fi-plus"></i> plus</li>
        <li class="minus"><i class="fi-minus"></i> minus</li>
        <li class="x"><i class="fi-x"></i> x</li>
        <li class="check"><i class="fi-check"></i> check</li>
        <li class="upload"><i class="fi-upload"></i> upload</li>
        <li class="download"><i class="fi-download"></i> download</li>
        <li class="widget"><i class="fi-widget"></i> widget</li>
        <li class="marker"><i class="fi-marker"></i> marker</li>
        <li class="refresh"><i class="fi-refresh"></i> refresh</li>
        <li class="home"><i class="fi-home"></i> home</li>
        <li class="trash"><i class="fi-trash"></i> trash</li>
        <li class="paperclip"><i class="fi-paperclip"></i> paperclip</li>
        <li class="lock"><i class="fi-lock"></i> lock</li>
        <li class="unlock"><i class="fi-unlock"></i> unlock</li>
        <li class="calendar"><i class="fi-calendar"></i> calendar</li>
        <li class="cloud"><i class="fi-cloud"></i> cloud</li>
        <li class="magnifying-glass"><i class="fi-magnifying-glass"></i> magnifying-glass</li>
        <li class="zoom-out"><i class="fi-zoom-out"></i> zoom-out</li>
        <li class="zoom-in"><i class="fi-zoom-in"></i> zoom-in</li>
        <li class="wrench"><i class="fi-wrench"></i> wrench</li>
        <li class="rss"><i class="fi-rss"></i> rss</li>
        <li class="share"><i class="fi-share"></i> share</li>
        <li class="flag"><i class="fi-flag"></i> flag</li>
        <li class="list-thumbnails"><i class="fi-list-thumbnails"></i> list-thumbnails</li>
        <li class="list"><i class="fi-list"></i> list</li>
        <li class="thumbnails"><i class="fi-thumbnails"></i> thumbnails</li>
        <li class="annotate"><i class="fi-annotate"></i> annotate</li>
        <li class="folder"><i class="fi-folder"></i> folder</li>
        <li class="folder-lock"><i class="fi-folder-lock"></i> folder-lock</li>
        <li class="folder-add"><i class="fi-folder-add"></i> folder-add</li>
        <li class="clock"><i class="fi-clock"></i> clock</li>
        <li class="play-video"><i class="fi-play-video"></i> play-video</li>
        <li class="crop"><i class="fi-crop"></i> crop</li>
        <li class="archive"><i class="fi-archive"></i> archive</li>
        <li class="pencil"><i class="fi-pencil"></i> pencil</li>
        <li class="graph-trend"><i class="fi-graph-trend"></i> graph-trend</li>
        <li class="graph-bar"><i class="fi-graph-bar"></i> graph-bar</li>
        <li class="graph-horizontal"><i class="fi-graph-horizontal"></i> graph-horizontal</li>
        <li class="graph-pie"><i class="fi-graph-pie"></i> graph-pie</li>
        <li class="checkbox"><i class="fi-checkbox"></i> checkbox</li>
        <li class="minus-circle"><i class="fi-minus-circle"></i> minus-circle</li>
        <li class="x-circle"><i class="fi-x-circle"></i> x-circle</li>
        <li class="eye"><i class="fi-eye"></i> eye</li>
        <li class="database"><i class="fi-database"></i> database</li>
        <li class="results"><i class="fi-results"></i> results</li>
        <li class="results-demographics"><i class="fi-results-demographics"></i> results-demographics</li>
        <li class="like"><i class="fi-like"></i> like</li>
        <li class="dislike"><i class="fi-dislike"></i> dislike</li>
        <li class="upload-cloud"><i class="fi-upload-cloud"></i> upload-cloud</li>
        <li class="camera"><i class="fi-camera"></i> camera</li>
        <li class="alert"><i class="fi-alert"></i> alert</li>
        <li class="bookmark"><i class="fi-bookmark"></i> bookmark</li>
        <li class="contrast"><i class="fi-contrast"></i> contrast</li>
        <li class="mail"><i class="fi-mail"></i> mail</li>
        <li class="video"><i class="fi-video"></i> video</li>
        <li class="phone"><i class="fi-telephone"></i> telephone</li>
        <li class="comment"><i class="fi-comment"></i> comment</li>
        <li class="comment-video"><i class="fi-comment-video"></i> comment-video</li>
        <li class="comment-quotes"><i class="fi-comment-quotes"></i> comment-quotes</li>
        <li class="comment-minus"><i class="fi-comment-minus"></i> comment-minus</li>
        <li class="comments"><i class="fi-comments"></i> comments</li>
        <li class="microphone"><i class="fi-microphone"></i> microphone</li>
        <li class="megaphone"><i class="fi-megaphone"></i> megaphone</li>
        <li class="sound"><i class="fi-sound"></i> sound</li>
        <li class="address-book"><i class="fi-address-book"></i> address-book</li>
        <li class="bluetooth"><i class="fi-bluetooth"></i> bluetooth</li>
        <li class="html5"><i class="fi-html5"></i> html5</li>
        <li class="css3"><i class="fi-css3"></i> css3</li>
        <li class="layout"><i class="fi-layout"></i> layout</li>
        <li class="web"><i class="fi-web"></i> web</li>
        <li class="foundation"><i class="fi-foundation"></i> foundation</li>
      </ul>

      <h2>Page Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="page"><i class="fi-page"></i> page</li>
        <li class="page-csv"><i class="fi-page-csv"></i> page-csv</li>
        <li class="page-doc"><i class="fi-page-export-csv"></i> page-doc</li>
        <li class="page-pdf"><i class="fi-page-export-csv"></i> page-pdf</li>
        <li class="page-export"><i class="fi-page-export"></i> page-export</li>
        <li class="page-export-csv"><i class="fi-page-export-csv"></i> page-export-csv</li>
        <li class="page-export-doc"><i class="fi-page-export-doc"></i> page-export-doc</li>
        <li class="page-export-pdf"><i class="fi-page-export-pdf"></i> page-export-pdf</li>
        <li class="page-add"><i class="fi-page-add"></i> page-add</li>
        <li class="page-remove"><i class="fi-page-remove"></i> page-remove</li>
        <li class="page-delete"><i class="fi-page-delete"></i> page-delete</li>
        <li class="page-edit"><i class="fi-page-edit"></i> page-edit</li>
        <li class="page-search"><i class="fi-page-search"></i> page-search</li>
        <li class="page-copy"><i class="fi-page-copy"></i> page-copy</li>
        <li class="page-filled"><i class="fi-page-filled"></i> page-filled</li>
        <li class="page-multiple"><i class="fi-page-multiple"></i> page-multiple</li>
      </ul>

      <h2>Arrow Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="arrow-up"><i class="fi-arrow-up"></i> arrow-up</li>
        <li class="arrow-right"><i class="fi-arrow-right"></i> arrow-right</li>
        <li class="arrow-down"><i class="fi-arrow-down"></i> arrow-down</li>
        <li class="arrow-left"><i class="fi-arrow-left"></i> arrow-left</li>
        <li class="arrows-out"><i class="fi-arrows-out"></i> arrows-out</li>
        <li class="arrows-in"><i class="fi-arrows-in"></i> arrows-in</li>
        <li class="arrows-expand"><i class="fi-arrows-expand"></i> arrows-expand</li>
        <li class="arrows-compress"><i class="fi-arrows-compress"></i> arrows-compress</li>
      </ul>

      <h2>People Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="torso"><i class="fi-torso"></i> torso</li>
        <li class="torso-female"><i class="fi-torso-female"></i> torso-female</li>
        <li class="torsos"><i class="fi-torsos"></i> torsos</li>
        <li class="torsos-female-male"><i class="fi-torsos-female-male"></i> torsos-female-male</li>
        <li class="torsos-male-female"><i class="fi-torsos-male-female"></i> torsos-male-female</li>
        <li class="torsos-all"><i class="fi-torsos-all"></i> torsos-all</li>
        <li class="torsos-all-female"><i class="fi-torsos-all-female"></i> torsos-all-female</li>
        <li class="torso-business"><i class="fi-torso-business"></i> torso-business</li>
      </ul>

      <h2>Device Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="monitor"><i class="fi-monitor"></i> monitor</li>
        <li class="laptop"><i class="fi-laptop"></i> laptop</li>
        <li class="tablet-portrait"><i class="fi-tablet-portrait"></i> tablet-portrait</li>
        <li class="tablet-landscape"><i class="fi-tablet-landscape"></i> tablet-landscape</li>
        <li class="mobile"><i class="fi-mobile"></i> mobile</li>
        <li class="mobile-signal"><i class="fi-mobile-signal"></i> mobile-signal</li>
        <li class="usb"><i class="fi-usb"></i> usb</li>
      </ul>

      <h2>Text Editor Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="bold"><i class="fi-bold"></i> bold</li>
        <li class="italic"><i class="fi-italic"></i> italic</li>
        <li class="underline"><i class="fi-underline"></i> underline</li>
        <li class="strikethrough"><i class="fi-strikethrough"></i> strike</li>
        <li class="text-color"><i class="fi-text-color"></i> text-color</li>
        <li class="background-color"><i class="fi-background-color"></i> background-color</li>
        <li class="superscript"><i class="fi-superscript"></i> superscript</li>
        <li class="subscript"><i class="fi-subscript"></i> subscript</li>
        <li class="align-left"><i class="fi-align-left"></i> align-left</li>
        <li class="align-center"><i class="fi-align-center"></i> align-center</li>
        <li class="align-right"><i class="fi-align-right"></i> align-right</li>
        <li class="align-justify"><i class="fi-align-justify"></i> align-justify</li>
        <li class="list-number"><i class="fi-list-number"></i> list-numbered</li>
        <li class="list-bullet"><i class="fi-list-bullet"></i> list-bullet</li>
        <li class="indent-more"><i class="fi-indent-more"></i> indent-more</li>
        <li class="indent-less"><i class="fi-indent-less"></i> indent-less</li>
        <li class="print"><i class="fi-print"></i> print</li>
        <li class="save"><i class="fi-save"></i> save</li>
        <li class="photo"><i class="fi-photo"></i> photo</li>
        <li class="filter"><i class="fi-filter"></i> filter</li>
        <li class="paint-bucket"><i class="fi-paint-bucket"></i> paint-bucket</li>
        <li class="link"><i class="fi-link"></i> link</li>
        <li class="unlink"><i class="fi-unlink"></i> unlink</li>
        <li class="quote"><i class="fi-quote"></i> quote</li>
      </ul>

      <h2>Media Control Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="play"><i class="fi-play"></i> play</li>
        <li class="stop"><i class="fi-stop"></i> stop</li>
        <li class="pause"><i class="fi-pause"></i> pause</li>
        <li class="previous"><i class="fi-previous"></i> previous</li>
        <li class="rewind"><i class="fi-rewind"></i> rewind</li>
        <li class="fast-forward"><i class="fi-fast-forward"></i> fast-forward</li>
        <li class="next"><i class="fi-next"></i> next</li>
        <li class="record"><i class="fi-record"></i> record</li>
        <li class="play-circle"><i class="fi-play-circle"></i> play-circle</li>
        <li class="volume-none"><i class="fi-volume-none"></i> volume-none</li>
        <li class="volume"><i class="fi-volume"></i> volume</li>
        <li class="volume-strike"><i class="fi-volume-strike"></i> volume-strike</li>
        <li class="loop"><i class="fi-loop"></i> loop</li>
        <li class="shuffle"><i class="fi-shuffle"></i> shuffle</li>
        <li class="eject"><i class="fi-eject"></i> eject</li>
        <li class="rewind-ten"><i class="fi-rewind-ten"></i> rewind-ten</li>
      </ul>

      <h2>Ecommerce Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="dollar"><i class="fi-dollar"></i> dollar</li>
        <li class="euro"><i class="fi-euro"></i> euro</li>
        <li class="pound"><i class="fi-pound"></i> pound</li>
        <li class="yen"><i class="fi-yen"></i> yen</li>
        <li class="bitcoin"><i class="fi-bitcoin"></i> bitcoin</li>
        <li class="bitcoin-circle"><i class="fi-bitcoin-circle"></i> bitcoin-circle</li>
        <li class="credit-card"><i class="fi-credit-card"></i> credit-card</li>
        <li class="shopping-cart"><i class="fi-shopping-cart"></i> shopping-cart</li>
        <li class="burst"><i class="fi-burst"></i> burst</li>
        <li class="burst-new"><i class="fi-burst-new"></i> burst-new</li>
        <li class="burst-sale"><i class="fi-burst-sale"></i> burst-sale</li>
        <li class="paypal"><i class="fi-paypal"></i> paypal</li>
        <li class="price-tag"><i class="fi-price-tag"></i> price-tag</li>
        <li class="pricetag-multiple"><i class="fi-pricetag-multiple"></i> pricetag-multiple</li>
        <li class="shopping-bag"><i class="fi-shopping-bag"></i> shopping-bag</li>
        <li class="dollar-bill"><i class="fi-dollar-bill"></i> dollar-bill</li>
      </ul>

      <h2>Accessibility Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="wheelchair"><i class="fi-wheelchair"></i> wheelchair</li>
        <li class="braille"><i class="fi-braille"></i> braille</li>
        <li class="closed-caption"><i class="fi-closed-caption"></i> closed-caption</li>
        <li class="blind"><i class="fi-blind"></i> blind</li>
        <li class="asl"><i class="fi-asl"></i> asl</li>
        <li class="hearing-aid"><i class="fi-hearing-aid"></i> hearing-aid</li>
        <li class="guide-dog"><i class="fi-guide-dog"></i> guide-dog</li>
        <li class="universal-access"><i class="fi-universal-access"></i> universal-access</li>
        <li class="telephone-accessible"><i class="fi-telephone-accessible"></i> telephone-accessible</li>
        <li class="elevator"><i class="fi-elevator"></i> elevator</li>
        <li class="male"><i class="fi-male"></i> male</li>
        <li class="female"><i class="fi-female"></i> female</li>
        <li class="male-female"><i class="fi-male-female"></i> male-female</li>
        <li class="male-symbol"><i class="fi-male-symbol"></i> male-symbol</li>
        <li class="female-symbol"><i class="fi-female-symbol"></i> female-symbol</li>
      </ul>

      <h2>Social &amp; Brand Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="social-500px"><i class="fi-social-500px"></i> social-500px</li>
        <li class="social-adobe"><i class="fi-social-adobe"></i> social-adobe</li>
        <li class="social-amazon"><i class="fi-social-amazon"></i> social-amazon</li>
        <li class="social-android"><i class="fi-social-android"></i> social-android</li>
        <li class="social-apple"><i class="fi-social-apple"></i> social-apple</li>
        <li class="social-behance"><i class="fi-social-behance"></i> social-behance</li>
        <li class="social-bing"><i class="fi-social-bing"></i> social-bing</li>
        <li class="social-blogger"><i class="fi-social-blogger"></i> social-blogger</li>
        <li class="social-delicious"><i class="fi-social-delicious"></i> social-delicious</li>
        <li class="social-designer-news"><i class="fi-social-designer-news"></i> social-designer-news</li>
        <li class="social-deviant-art"><i class="fi-social-deviant-art"></i> social-deviant-art</li>
        <li class="social-digg"><i class="fi-social-digg"></i> social-digg</li>
        <li class="social-dribbble"><i class="fi-social-dribbble"></i> social-dribbble</li>
        <li class="social-drive"><i class="fi-social-drive"></i> social-drive</li>
        <li class="social-dropbox"><i class="fi-social-dropbox"></i> social-dropbox</li>
        <li class="social-evernote"><i class="fi-social-evernote"></i> social-evernote</li>
        <li class="social-facebook"><i class="fi-social-facebook"></i> social-facebook</li>
        <li class="social-flickr"><i class="fi-social-flickr"></i> social-flickr</li>
        <li class="social-forrst"><i class="fi-social-forrst"></i> social-forrst</li>
        <li class="social-foursquare"><i class="fi-social-foursquare"></i> social-foursquare</li>
        <li class="social-game-center"><i class="fi-social-game-center"></i> social-game-center</li>
        <li class="social-github"><i class="fi-social-github"></i> social-github</li>
        <li class="social-google-plus"><i class="fi-social-google-plus"></i> social-google-plus</li>
        <li class="social-hacker-news"><i class="fi-social-hacker-news"></i> social-hacker-news</li>
        <li class="social-hi5"><i class="fi-social-hi5"></i> social-hi5</li>
        <li class="social-instagram"><i class="fi-social-instagram"></i> social-instagram</li>
        <li class="social-joomla"><i class="fi-social-joomla"></i> social-joomla</li>
        <li class="social-lastfm"><i class="fi-social-lastfm"></i> social-lastfm</li>
        <li class="social-linkedin"><i class="fi-social-linkedin"></i> social-linkedin</li>
        <li class="social-medium"><i class="fi-social-medium"></i> social-medium</li>
        <li class="social-myspace"><i class="fi-social-myspace"></i> social-myspace</li>
        <li class="social-orkut"><i class="fi-social-orkut"></i> social-orkut</li>
        <li class="social-path"><i class="fi-social-path"></i> social-path</li>
        <li class="social-picasa"><i class="fi-social-picasa"></i> social-picasa</li>
        <li class="social-pinterest"><i class="fi-social-pinterest"></i> social-pinterest</li>
        <li class="social-rdio"><i class="fi-social-rdio"></i> social-rdio</li>
        <li class="social-reddit"><i class="fi-social-reddit"></i> social-reddit</li>
        <li class="social-skype"><i class="fi-social-skype"></i> social-skype</li>
        <li class="social-skillshare"><i class="fi-social-skillshare"></i> social-skillshare</li>
        <li class="social-smashing-mag"><i class="fi-social-smashing-mag"></i> social-smashing-mag</li>
        <li class="social-snapchat"><i class="fi-social-snapchat"></i> social-snapchat</li>
        <li class="social-spotify"><i class="fi-social-spotify"></i> social-spotify</li>
        <li class="social-squidoo"><i class="fi-social-squidoo"></i> social-squidoo</li>
        <li class="social-stack-overflow"><i class="fi-social-stack-overflow"></i> social-stack-overflow</li>
        <li class="social-steam"><i class="fi-social-steam"></i> social-steam</li>
        <li class="social-stumbleupon"><i class="fi-social-stumbleupon"></i> social-stumbleupon</li>
        <li class="social-treehouse"><i class="fi-social-treehouse"></i> social-treehouse</li>
        <li class="social-tumblr"><i class="fi-social-tumblr"></i> social-tumblr</li>
        <li class="social-twitter"><i class="fi-social-twitter"></i> social-twitter</li>
        <li class="social-vimeo"><i class="fi-social-vimeo"></i> social-vimeo</li>
        <li class="social-windows"><i class="fi-social-windows"></i> social-windows</li>
        <li class="social-xbox-20"><i class="fi-social-xbox-20"></i> social-xbox</li>
        <li class="social-yahoo"><i class="fi-social-yahoo"></i> social-yahoo</li>
        <li class="social-yelp"><i class="fi-social-yelp"></i> social-yelp</li>
        <li class="social-youtube"><i class="fi-social-youtube"></i> social-youtube</li>
        <li class="social-zerply"><i class="fi-social-zerply"></i> social-zerply</li>
        <li class="social-zurb"><i class="fi-social-zurb"></i> social-zurb</li>
      </ul>

      <h2>Miscellaneous Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="compass"><i class="fi-compass"></i> compass</li>
        <li class="music"><i class="fi-music"></i> music</li>
        <li class="lightbulb"><i class="fi-lightbulb"></i> lightbulb</li>
        <li class="battery-full"><i class="fi-battery-full"></i> battery-full</li>
        <li class="battery-half"><i class="fi-battery-half"></i> battery-half</li>
        <li class="battery-empty"><i class="fi-battery-empty"></i> battery-empty</li>
        <li class="projection-screen"><i class="fi-projection-screen"></i> projection-screen</li>
        <li class="info"><i class="fi-info"></i> info</li>
        <li class="power"><i class="fi-power"></i> power</li>
        <li class="asterisk"><i class="fi-asterisk"></i> asterisk</li>
        <li class="at-sign"><i class="fi-at-sign"></i> at-sign</li>
        <li class="key"><i class="fi-key"></i> key</li>
        <li class="ticket"><i class="fi-ticket"></i> ticket</li>
        <li class="book"><i class="fi-book"></i> book</li>
        <li class="book-bookmark"><i class="fi-book-bookmark"></i> book-bookmark</li>
        <li class="anchor"><i class="fi-anchor"></i> anchor</li>
        <li class="puzzle"><i class="fi-puzzle"></i> puzzle</li>
        <li class="foot"><i class="fi-foot"></i> foot</li>
        <li class="paw"><i class="fi-paw"></i> paw</li>
        <li class="mountains"><i class="fi-mountains"></i> mountains</li>
        <li class="trees"><i class="fi-trees"></i> trees</li>
        <li class="sheriff-badge"><i class="fi-sheriff-badge"></i> sheriff-badge</li>
        <li class="first-aid"><i class="fi-first-aid"></i> first-aid</li>
        <li class="trophy"><i class="fi-trophy"></i> trophy</li>
        <li class="prohibited"><i class="fi-prohibited"></i> prohibited</li>
        <li class="no-dogs"><i class="fi-no-dogs"></i> no-dogs</li>
        <li class="no-smoking"><i class="fi-no-smoking"></i> no-smoking</li>
        <li class="safety-cone"><i class="fi-safety-cone"></i> safety-cone</li>
        <li class="shield"><i class="fi-shield"></i> shield</li>
        <li class="crown"><i class="fi-crown"></i> crown</li>
        <li class="target"><i class="fi-target"></i> target</li>
        <li class="target-two"><i class="fi-target-two"></i> target-two</li>
        <li class="die-one"><i class="fi-die-one"></i> die-one</li>
        <li class="die-two"><i class="fi-die-two"></i> die-two</li>
        <li class="die-three"><i class="fi-die-three"></i> die-three</li>
        <li class="die-four"><i class="fi-die-four"></i> die-four</li>
        <li class="die-five"><i class="fi-die-five"></i> die-five</li>
        <li class="die-six"><i class="fi-die-six"></i> die-six</li>
        <li class="skull"><i class="fi-skull"></i> skull</li>
        <li class="map"><i class="fi-map"></i> map</li>
        <li class="clipboard"><i class="fi-clipboard"></i> clipboard</li>
        <li class="clipboard-pencil"><i class="fi-clipboard-pencil"></i> clipboard-pencil</li>
        <li class="clipboard-notes"><i class="fi-clipboard-notes"></i> clipboard-notes</li>
      </ul>
    </div></div>
</section>

<section class="intro">
  <div class="row">
    <div class="large-4 columns">
      <h5>Use 283 icons with 1 font</h5>
      <p>A custom collection of 283 icons that are stored in a handy web font.</p>
    </div>
    <div class="large-4 columns">
      <h5>Style 'em with CSS</h5>
      <p>A couple lines of CSS and the right markup will get you going in no time.</p>
    </div>
    <div class="large-4 columns">
      <h5>Create infinite variations</h5>
      <p>Easily customize these icons to be any size, color and style in CSS.</p>
    </div>
  </div>
</section>

