<section class="main">
  <div class="row">
    <div class="large-12 columns">
      <h1>Foundation Icon Fonts 3</h1> 

      <h2>General Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="heart"><span class="fi-heart"></span> heart</li>
        <li class="star"><span class="fi-star"></span> star</li>
        <li class="plus"><span class="fi-plus"></span> plus</li>
        <li class="minus"><span class="fi-minus"></span> minus</li>
        <li class="x"><span class="fi-x"></span> x</li>
        <li class="check"><span class="fi-check"></span> check</li>
        <li class="upload"><span class="fi-upload"></span> upload</li>
        <li class="download"><span class="fi-download"></span> download</li>
        <li class="widget"><span class="fi-widget"></span> widget</li>
        <li class="marker"><span class="fi-marker"></span> marker</li>
        <li class="refresh"><span class="fi-refresh"></span> refresh</li>
        <li class="home"><span class="fi-home"></span> home</li>
        <li class="trash"><span class="fi-trash"></span> trash</li>
        <li class="paperclip"><span class="fi-paperclip"></span> paperclip</li>
        <li class="lock"><span class="fi-lock"></span> lock</li>
        <li class="unlock"><span class="fi-unlock"></span> unlock</li>
        <li class="calendar"><span class="fi-calendar"></span> calendar</li>
        <li class="cloud"><span class="fi-cloud"></span> cloud</li>
        <li class="magnifying-glass"><span class="fi-magnifying-glass"></span> magnifying-glass</li>
        <li class="zoom-out"><span class="fi-zoom-out"></span> zoom-out</li>
        <li class="zoom-in"><span class="fi-zoom-in"></span> zoom-in</li>
        <li class="wrench"><span class="fi-wrench"></span> wrench</li>
        <li class="rss"><span class="fi-rss"></span> rss</li>
        <li class="share"><span class="fi-share"></span> share</li>
        <li class="flag"><span class="fi-flag"></span> flag</li>
        <li class="list-thumbnails"><span class="fi-list-thumbnails"></span> list-thumbnails</li>
        <li class="list"><span class="fi-list"></span> list</li>
        <li class="thumbnails"><span class="fi-thumbnails"></span> thumbnails</li>
        <li class="annotate"><span class="fi-annotate"></span> annotate</li>
        <li class="folder"><span class="fi-folder"></span> folder</li>
        <li class="folder-lock"><span class="fi-folder-lock"></span> folder-lock</li>
        <li class="folder-add"><span class="fi-folder-add"></span> folder-add</li>
        <li class="clock"><span class="fi-clock"></span> clock</li>
        <li class="play-video"><span class="fi-play-video"></span> play-video</li>
        <li class="crop"><span class="fi-crop"></span> crop</li>
        <li class="archive"><span class="fi-archive"></span> archive</li>
        <li class="pencil"><span class="fi-pencil"></span> pencil</li>
        <li class="graph-trend"><span class="fi-graph-trend"></span> graph-trend</li>
        <li class="graph-bar"><span class="fi-graph-bar"></span> graph-bar</li>
        <li class="graph-horizontal"><span class="fi-graph-horizontal"></span> graph-horizontal</li>
        <li class="graph-pie"><span class="fi-graph-pie"></span> graph-pie</li>
        <li class="checkbox"><span class="fi-checkbox"></span> checkbox</li>
        <li class="minus-circle"><span class="fi-minus-circle"></span> minus-circle</li>
        <li class="x-circle"><span class="fi-x-circle"></span> x-circle</li>
        <li class="eye"><span class="fi-eye"></span> eye</li>
        <li class="database"><span class="fi-database"></span> database</li>
        <li class="results"><span class="fi-results"></span> results</li>
        <li class="results-demographics"><span class="fi-results-demographics"></span> results-demographics</li>
        <li class="like"><span class="fi-like"></span> like</li>
        <li class="dislike"><span class="fi-dislike"></span> dislike</li>
        <li class="upload-cloud"><span class="fi-upload-cloud"></span> upload-cloud</li>
        <li class="camera"><span class="fi-camera"></span> camera</li>
        <li class="alert"><span class="fi-alert"></span> alert</li>
        <li class="bookmark"><span class="fi-bookmark"></span> bookmark</li>
        <li class="contrast"><span class="fi-contrast"></span> contrast</li>
        <li class="mail"><span class="fi-mail"></span> mail</li>
        <li class="video"><span class="fi-video"></span> video</li>
        <li class="phone"><span class="fi-telephone"></span> telephone</li>
        <li class="comment"><span class="fi-comment"></span> comment</li>
        <li class="comment-video"><span class="fi-comment-video"></span> comment-video</li>
        <li class="comment-quotes"><span class="fi-comment-quotes"></span> comment-quotes</li>
        <li class="comment-minus"><span class="fi-comment-minus"></span> comment-minus</li>
        <li class="comments"><span class="fi-comments"></span> comments</li>
        <li class="microphone"><span class="fi-microphone"></span> microphone</li>
        <li class="megaphone"><span class="fi-megaphone"></span> megaphone</li>
        <li class="sound"><span class="fi-sound"></span> sound</li>
        <li class="address-book"><span class="fi-address-book"></span> address-book</li>
        <li class="bluetooth"><span class="fi-bluetooth"></span> bluetooth</li>
        <li class="html5"><span class="fi-html5"></span> html5</li>
        <li class="css3"><span class="fi-css3"></span> css3</li>
        <li class="layout"><span class="fi-layout"></span> layout</li>
        <li class="web"><span class="fi-web"></span> web</li>
        <li class="foundation"><span class="fi-foundation"></span> foundation</li>
      </ul>

      <h2>Page Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="page"><span class="fi-page"></span> page</li>
        <li class="page-csv"><span class="fi-page-csv"></span> page-csv</li>
        <li class="page-doc"><span class="fi-page-export-csv"></span> page-doc</li>
        <li class="page-pdf"><span class="fi-page-export-csv"></span> page-pdf</li>
        <li class="page-export"><span class="fi-page-export"></span> page-export</li>
        <li class="page-export-csv"><span class="fi-page-export-csv"></span> page-export-csv</li>
        <li class="page-export-doc"><span class="fi-page-export-doc"></span> page-export-doc</li>
        <li class="page-export-pdf"><span class="fi-page-export-pdf"></span> page-export-pdf</li>
        <li class="page-add"><span class="fi-page-add"></span> page-add</li>
        <li class="page-remove"><span class="fi-page-remove"></span> page-remove</li>
        <li class="page-delete"><span class="fi-page-delete"></span> page-delete</li>
        <li class="page-edit"><span class="fi-page-edit"></span> page-edit</li>
        <li class="page-search"><span class="fi-page-search"></span> page-search</li>
        <li class="page-copy"><span class="fi-page-copy"></span> page-copy</li>
        <li class="page-filled"><span class="fi-page-filled"></span> page-filled</li>
        <li class="page-multiple"><span class="fi-page-multiple"></span> page-multiple</li>
      </ul>

      <h2>Arrow Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="arrow-up"><span class="fi-arrow-up"></span> arrow-up</li>
        <li class="arrow-right"><span class="fi-arrow-right"></span> arrow-right</li>
        <li class="arrow-down"><span class="fi-arrow-down"></span> arrow-down</li>
        <li class="arrow-left"><span class="fi-arrow-left"></span> arrow-left</li>
        <li class="arrows-out"><span class="fi-arrows-out"></span> arrows-out</li>
        <li class="arrows-in"><span class="fi-arrows-in"></span> arrows-in</li>
        <li class="arrows-expand"><span class="fi-arrows-expand"></span> arrows-expand</li>
        <li class="arrows-compress"><span class="fi-arrows-compress"></span> arrows-compress</li>
      </ul>

      <h2>People Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="torso"><span class="fi-torso"></span> torso</li>
        <li class="torso-female"><span class="fi-torso-female"></span> torso-female</li>
        <li class="torsos"><span class="fi-torsos"></span> torsos</li>
        <li class="torsos-female-male"><span class="fi-torsos-female-male"></span> torsos-female-male</li>
        <li class="torsos-male-female"><span class="fi-torsos-male-female"></span> torsos-male-female</li>
        <li class="torsos-all"><span class="fi-torsos-all"></span> torsos-all</li>
        <li class="torsos-all-female"><span class="fi-torsos-all-female"></span> torsos-all-female</li>
        <li class="torso-business"><span class="fi-torso-business"></span> torso-business</li>
      </ul>

      <h2>Device Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="monitor"><span class="fi-monitor"></span> monitor</li>
        <li class="laptop"><span class="fi-laptop"></span> laptop</li>
        <li class="tablet-portrait"><span class="fi-tablet-portrait"></span> tablet-portrait</li>
        <li class="tablet-landscape"><span class="fi-tablet-landscape"></span> tablet-landscape</li>
        <li class="mobile"><span class="fi-mobile"></span> mobile</li>
        <li class="mobile-signal"><span class="fi-mobile-signal"></span> mobile-signal</li>
        <li class="usb"><span class="fi-usb"></span> usb</li>
      </ul>

      <h2>Text Editor Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="bold"><span class="fi-bold"></span> bold</li>
        <li class="italic"><span class="fi-italic"></span> italic</li>
        <li class="underline"><span class="fi-underline"></span> underline</li>
        <li class="strikethrough"><span class="fi-strikethrough"></span> strike</li>
        <li class="text-color"><span class="fi-text-color"></span> text-color</li>
        <li class="background-color"><span class="fi-background-color"></span> background-color</li>
        <li class="superscript"><span class="fi-superscript"></span> superscript</li>
        <li class="subscript"><span class="fi-subscript"></span> subscript</li>
        <li class="align-left"><span class="fi-align-left"></span> align-left</li>
        <li class="align-center"><span class="fi-align-center"></span> align-center</li>
        <li class="align-right"><span class="fi-align-right"></span> align-right</li>
        <li class="align-justify"><span class="fi-align-justify"></span> align-justify</li>
        <li class="list-number"><span class="fi-list-number"></span> list-numbered</li>
        <li class="list-bullet"><span class="fi-list-bullet"></span> list-bullet</li>
        <li class="indent-more"><span class="fi-indent-more"></span> indent-more</li>
        <li class="indent-less"><span class="fi-indent-less"></span> indent-less</li>
        <li class="print"><span class="fi-print"></span> print</li>
        <li class="save"><span class="fi-save"></span> save</li>
        <li class="photo"><span class="fi-photo"></span> photo</li>
        <li class="filter"><span class="fi-filter"></span> filter</li>
        <li class="paint-bucket"><span class="fi-paint-bucket"></span> paint-bucket</li>
        <li class="link"><span class="fi-link"></span> link</li>
        <li class="unlink"><span class="fi-unlink"></span> unlink</li>
        <li class="quote"><span class="fi-quote"></span> quote</li>
      </ul>

      <h2>Media Control Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="play"><span class="fi-play"></span> play</li>
        <li class="stop"><span class="fi-stop"></span> stop</li>
        <li class="pause"><span class="fi-pause"></span> pause</li>
        <li class="previous"><span class="fi-previous"></span> previous</li>
        <li class="rewind"><span class="fi-rewind"></span> rewind</li>
        <li class="fast-forward"><span class="fi-fast-forward"></span> fast-forward</li>
        <li class="next"><span class="fi-next"></span> next</li>
        <li class="record"><span class="fi-record"></span> record</li>
        <li class="play-circle"><span class="fi-play-circle"></span> play-circle</li>
        <li class="volume-none"><span class="fi-volume-none"></span> volume-none</li>
        <li class="volume"><span class="fi-volume"></span> volume</li>
        <li class="volume-strike"><span class="fi-volume-strike"></span> volume-strike</li>
        <li class="loop"><span class="fi-loop"></span> loop</li>
        <li class="shuffle"><span class="fi-shuffle"></span> shuffle</li>
        <li class="eject"><span class="fi-eject"></span> eject</li>
        <li class="rewind-ten"><span class="fi-rewind-ten"></span> rewind-ten</li>
      </ul>

      <h2>Ecommerce Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="dollar"><span class="fi-dollar"></span> dollar</li>
        <li class="euro"><span class="fi-euro"></span> euro</li>
        <li class="pound"><span class="fi-pound"></span> pound</li>
        <li class="yen"><span class="fi-yen"></span> yen</li>
        <li class="bitcoin"><span class="fi-bitcoin"></span> bitcoin</li>
        <li class="bitcoin-circle"><span class="fi-bitcoin-circle"></span> bitcoin-circle</li>
        <li class="credit-card"><span class="fi-credit-card"></span> credit-card</li>
        <li class="shopping-cart"><span class="fi-shopping-cart"></span> shopping-cart</li>
        <li class="burst"><span class="fi-burst"></span> burst</li>
        <li class="burst-new"><span class="fi-burst-new"></span> burst-new</li>
        <li class="burst-sale"><span class="fi-burst-sale"></span> burst-sale</li>
        <li class="paypal"><span class="fi-paypal"></span> paypal</li>
        <li class="price-tag"><span class="fi-price-tag"></span> price-tag</li>
        <li class="pricetag-multiple"><span class="fi-pricetag-multiple"></span> pricetag-multiple</li>
        <li class="shopping-bag"><span class="fi-shopping-bag"></span> shopping-bag</li>
        <li class="dollar-bill"><span class="fi-dollar-bill"></span> dollar-bill</li>
      </ul>

      <h2>Accessibility Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="wheelchair"><span class="fi-wheelchair"></span> wheelchair</li>
        <li class="braille"><span class="fi-braille"></span> braille</li>
        <li class="closed-caption"><span class="fi-closed-caption"></span> closed-caption</li>
        <li class="blind"><span class="fi-blind"></span> blind</li>
        <li class="asl"><span class="fi-asl"></span> asl</li>
        <li class="hearing-aid"><span class="fi-hearing-aid"></span> hearing-aid</li>
        <li class="guide-dog"><span class="fi-guide-dog"></span> guide-dog</li>
        <li class="universal-access"><span class="fi-universal-access"></span> universal-access</li>
        <li class="telephone-accessible"><span class="fi-telephone-accessible"></span> telephone-accessible</li>
        <li class="elevator"><span class="fi-elevator"></span> elevator</li>
        <li class="male"><span class="fi-male"></span> male</li>
        <li class="female"><span class="fi-female"></span> female</li>
        <li class="male-female"><span class="fi-male-female"></span> male-female</li>
        <li class="male-symbol"><span class="fi-male-symbol"></span> male-symbol</li>
        <li class="female-symbol"><span class="fi-female-symbol"></span> female-symbol</li>
      </ul>

      <h2>Social &amp; Brand Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="social-500px"><span class="fi-social-500px"></span> social-500px</li>
        <li class="social-adobe"><span class="fi-social-adobe"></span> social-adobe</li>
        <li class="social-amazon"><span class="fi-social-amazon"></span> social-amazon</li>
        <li class="social-android"><span class="fi-social-android"></span> social-android</li>
        <li class="social-apple"><span class="fi-social-apple"></span> social-apple</li>
        <li class="social-behance"><span class="fi-social-behance"></span> social-behance</li>
        <li class="social-bing"><span class="fi-social-bing"></span> social-bing</li>
        <li class="social-blogger"><span class="fi-social-blogger"></span> social-blogger</li>
        <li class="social-delicious"><span class="fi-social-delicious"></span> social-delicious</li>
        <li class="social-designer-news"><span class="fi-social-designer-news"></span> social-designer-news</li>
        <li class="social-deviant-art"><span class="fi-social-deviant-art"></span> social-deviant-art</li>
        <li class="social-digg"><span class="fi-social-digg"></span> social-digg</li>
        <li class="social-dribbble"><span class="fi-social-dribbble"></span> social-dribbble</li>
        <li class="social-drive"><span class="fi-social-drive"></span> social-drive</li>
        <li class="social-dropbox"><span class="fi-social-dropbox"></span> social-dropbox</li>
        <li class="social-evernote"><span class="fi-social-evernote"></span> social-evernote</li>
        <li class="social-facebook"><span class="fi-social-facebook"></span> social-facebook</li>
        <li class="social-flickr"><span class="fi-social-flickr"></span> social-flickr</li>
        <li class="social-forrst"><span class="fi-social-forrst"></span> social-forrst</li>
        <li class="social-foursquare"><span class="fi-social-foursquare"></span> social-foursquare</li>
        <li class="social-game-center"><span class="fi-social-game-center"></span> social-game-center</li>
        <li class="social-github"><span class="fi-social-github"></span> social-github</li>
        <li class="social-google-plus"><span class="fi-social-google-plus"></span> social-google-plus</li>
        <li class="social-hacker-news"><span class="fi-social-hacker-news"></span> social-hacker-news</li>
        <li class="social-hi5"><span class="fi-social-hi5"></span> social-hi5</li>
        <li class="social-instagram"><span class="fi-social-instagram"></span> social-instagram</li>
        <li class="social-joomla"><span class="fi-social-joomla"></span> social-joomla</li>
        <li class="social-lastfm"><span class="fi-social-lastfm"></span> social-lastfm</li>
        <li class="social-linkedin"><span class="fi-social-linkedin"></span> social-linkedin</li>
        <li class="social-medium"><span class="fi-social-medium"></span> social-medium</li>
        <li class="social-myspace"><span class="fi-social-myspace"></span> social-myspace</li>
        <li class="social-orkut"><span class="fi-social-orkut"></span> social-orkut</li>
        <li class="social-path"><span class="fi-social-path"></span> social-path</li>
        <li class="social-picasa"><span class="fi-social-picasa"></span> social-picasa</li>
        <li class="social-pinterest"><span class="fi-social-pinterest"></span> social-pinterest</li>
        <li class="social-rdio"><span class="fi-social-rdio"></span> social-rdio</li>
        <li class="social-reddit"><span class="fi-social-reddit"></span> social-reddit</li>
        <li class="social-skype"><span class="fi-social-skype"></span> social-skype</li>
        <li class="social-skillshare"><span class="fi-social-skillshare"></span> social-skillshare</li>
        <li class="social-smashing-mag"><span class="fi-social-smashing-mag"></span> social-smashing-mag</li>
        <li class="social-snapchat"><span class="fi-social-snapchat"></span> social-snapchat</li>
        <li class="social-spotify"><span class="fi-social-spotify"></span> social-spotify</li>
        <li class="social-squidoo"><span class="fi-social-squidoo"></span> social-squidoo</li>
        <li class="social-stack-overflow"><span class="fi-social-stack-overflow"></span> social-stack-overflow</li>
        <li class="social-steam"><span class="fi-social-steam"></span> social-steam</li>
        <li class="social-stumbleupon"><span class="fi-social-stumbleupon"></span> social-stumbleupon</li>
        <li class="social-treehouse"><span class="fi-social-treehouse"></span> social-treehouse</li>
        <li class="social-tumblr"><span class="fi-social-tumblr"></span> social-tumblr</li>
        <li class="social-twitter"><span class="fi-social-twitter"></span> social-twitter</li>
        <li class="social-vimeo"><span class="fi-social-vimeo"></span> social-vimeo</li>
        <li class="social-windows"><span class="fi-social-windows"></span> social-windows</li>
        <li class="social-xbox-20"><span class="fi-social-xbox-20"></span> social-xbox</li>
        <li class="social-yahoo"><span class="fi-social-yahoo"></span> social-yahoo</li>
        <li class="social-yelp"><span class="fi-social-yelp"></span> social-yelp</li>
        <li class="social-youtube"><span class="fi-social-youtube"></span> social-youtube</li>
        <li class="social-zerply"><span class="fi-social-zerply"></span> social-zerply</li>
        <li class="social-zurb"><span class="fi-social-zurb"></span> social-zurb</li>
      </ul>

      <h2>Miscellaneous Icons</h2>
      <ul class="small-block-grid-2 large-block-grid-4">
        <li class="compass"><span class="fi-compass"></span> compass</li>
        <li class="music"><span class="fi-music"></span> music</li>
        <li class="lightbulb"><span class="fi-lightbulb"></span> lightbulb</li>
        <li class="battery-full"><span class="fi-battery-full"></span> battery-full</li>
        <li class="battery-half"><span class="fi-battery-half"></span> battery-half</li>
        <li class="battery-empty"><span class="fi-battery-empty"></span> battery-empty</li>
        <li class="projection-screen"><span class="fi-projection-screen"></span> projection-screen</li>
        <li class="info"><span class="fi-info"></span> info</li>
        <li class="power"><span class="fi-power"></span> power</li>
        <li class="asterisk"><span class="fi-asterisk"></span> asterisk</li>
        <li class="at-sign"><span class="fi-at-sign"></span> at-sign</li>
        <li class="key"><span class="fi-key"></span> key</li>
        <li class="ticket"><span class="fi-ticket"></span> ticket</li>
        <li class="book"><span class="fi-book"></span> book</li>
        <li class="book-bookmark"><span class="fi-book-bookmark"></span> book-bookmark</li>
        <li class="anchor"><span class="fi-anchor"></span> anchor</li>
        <li class="puzzle"><span class="fi-puzzle"></span> puzzle</li>
        <li class="foot"><span class="fi-foot"></span> foot</li>
        <li class="paw"><span class="fi-paw"></span> paw</li>
        <li class="mountains"><span class="fi-mountains"></span> mountains</li>
        <li class="trees"><span class="fi-trees"></span> trees</li>
        <li class="sheriff-badge"><span class="fi-sheriff-badge"></span> sheriff-badge</li>
        <li class="first-aid"><span class="fi-first-aid"></span> first-aid</li>
        <li class="trophy"><span class="fi-trophy"></span> trophy</li>
        <li class="prohibited"><span class="fi-prohibited"></span> prohibited</li>
        <li class="no-dogs"><span class="fi-no-dogs"></span> no-dogs</li>
        <li class="no-smoking"><span class="fi-no-smoking"></span> no-smoking</li>
        <li class="safety-cone"><span class="fi-safety-cone"></span> safety-cone</li>
        <li class="shield"><span class="fi-shield"></span> shield</li>
        <li class="crown"><span class="fi-crown"></span> crown</li>
        <li class="target"><span class="fi-target"></span> target</li>
        <li class="target-two"><span class="fi-target-two"></span> target-two</li>
        <li class="die-one"><span class="fi-die-one"></span> die-one</li>
        <li class="die-two"><span class="fi-die-two"></span> die-two</li>
        <li class="die-three"><span class="fi-die-three"></span> die-three</li>
        <li class="die-four"><span class="fi-die-four"></span> die-four</li>
        <li class="die-five"><span class="fi-die-five"></span> die-five</li>
        <li class="die-six"><span class="fi-die-six"></span> die-six</li>
        <li class="skull"><span class="fi-skull"></span> skull</li>
        <li class="map"><span class="fi-map"></span> map</li>
        <li class="clipboard"><span class="fi-clipboard"></span> clipboard</li>
        <li class="clipboard-pencil"><span class="fi-clipboard-pencil"></span> clipboard-pencil</li>
        <li class="clipboard-notes"><span class="fi-clipboard-notes"></span> clipboard-notes</li>
      </ul>
    </div>
  </div>
</section>

<section class="intro">
  <div class="row">
    <div class="large-4 columns">
      <h5>Use 283 icons with 1 font</h5>
      <p>A custom collection of 283 icons that are stored in a handy web font.</p>
    </div>
    <div class="large-4 columns">
      <h5>Style 'em with CSS</h5>
      <p>A couple lines of CSS and the right markup will get you going in no time.</p>
    </div>
    <div class="large-4 columns">
      <h5>Create infinite variations</h5>
      <p>Easily customize these icons to be any size, color and style in CSS.</p>
    </div>
  </div>
</section>