    <footer class="row">
      <div class="large-12 columns">
        <p class="copyright">© <?php print date('Y'); ?> Typomedia Foundation. All rights reserved. Powered by Phalcon PHP and Foundation.</p>
      </div>
    </footer>

    
    <?php print $this->tag->javascriptInclude('js/foundation/vendor/jquery.js'); ?>
    <?php print $this->tag->javascriptInclude('js/foundation/foundation.min.js'); ?>
    <script>
      $(document).foundation();
    </script>