    <!--<div class="zurb-footer-bottom">
      <div class="row">
        <div class="medium-4 medium-4 push-8 columns">
          <ul class="home-social">
            <li><a href="http://www.twitter.com/ZURB" class="twitter"></a></li>
            <li><a href="http://www.facebook.com/ZURB" class="facebook"></a></li>
            <li><a href="http://zurb.com/contact" class="mail"></a></li>
          </ul>
        </div>
        <div class="medium-8 medium-8 pull-4 columns">
          <a href="http://www.zurb.com" class="zurb-logo regular"></a>
          <ul class="zurb-links">
            <li><a href="http://zurb.com/about">About</a></li>
            <li><a href="http://zurb.com/blog">Blog</a></li>
            <li><a href="http://zurb.com/news">News<span class="show-for-medium-up"> &amp; Events</span></a></li>
            <li><a href="http://zurb.com/contact">Contact</a></li>
            <li><a href="http://zurb.com/sitemap">Sitemap</a></li>
          </ul>
          <p class="copyright">© 1998–2015 ZURB, Inc. All rights reserved.</p>
        </div>
      </div>
    </div>-->

    <footer>
      <div class="row">
        <div class="large-12 columns">
          <p class="copyright">© <?php print date('Y'); ?> Typomedia Foundation. All rights reserved. Powered by <a href="http://phalconphp.com" target="_blank">Phalcon PHP</a> and <a href="http://zurb.com/about" target="_blank">ZURB Foundation</a>.</p>
        </div>
      </div>
    </footer>

    
    <?php print $this->tag->javascriptInclude('js/foundation/vendor/jquery.js'); ?>
    <?php print $this->tag->javascriptInclude('js/foundation/foundation.min.js'); ?>
    <script>
      $(document).foundation();
    </script>