<section class="intro">
  <div class="row">
    <div class="small-8 columns">
      <h3>Frontend build with Foundation!</h3>
      <h4 class="subheader">The most advanced responsive frontend framework in the world.</h4>
    </div>
    <div class="small-4 columns">
      <?php print $this->tag->linkTo(array('foundation', "Check It Out!", 'class' => 'button right')); ?>
    </div>
  </div>
</section>