<section id="homepage-hero">
  <div class="row">
    <div class="medium-7 large-6 columns">
      <h1>Welcome to Phalconium</h1><br>
      <h3>The most advanced responsive <br class="hide-for-small">WordPress theme in the world.</h3>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="large-4 medium-6 columns">
      <?php print $this->tag->linkTo(array('docs', "Getting Started", 'class' => 'large button hide-for-small')); ?>
      <?php print $this->tag->linkTo(array('docs', "Getting Started", 'class' => 'small button show-for-small')); ?>
    </div>
  </div>
  <div class="floatingyeti">
    <img src="http://foundation.zurb.com/assets/img/homepage/hero-image.svg">
  </div>
</section>

<section class="apps-promo">
  <div class="row">
    <div class="small-8 columns">
      <h3>Build with Foundation!</h3>
      <p>The most advanced responsive front-end framework in the world.</p>
    </div>
    <div class="small-4 columns">
      <?php print $this->tag->linkTo(array('foundation', "Check It Out!", 'class' => 'button right')); ?>
    </div>
  </div>
</section>
