<nav class="top-bar" data-topbar="">
  <ul class="title-area">
    <li class="name"><h1><?php print $this->tag->linkTo("/", "Phalconium"); ?></h1></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li class="has-dropdown not-click">
        <a href="develop/build.html" class="">Develop</a>
        <ul class="dropdown"><li class="title back js-generated"><h5><a href="javascript:void(0)">Back</a></h5></li><li class="parent-link show-for-small"><a class="parent-link js-generated" href="develop/build.html">Develop</a></li>
          <li><?php print $this->tag->linkTo("phalcon", "Phalcon"); ?></li>
          <li><?php print $this->tag->linkTo("foundation", "Foundation"); ?></li>
          <li><a href="develop/resources.html">Resources</a></li>
          <li><a href="develop/contribute.html">Contribute</a></li>
        </ul>
      </li>
      <li class="divider"></li>
      <li>
        <?php print $this->tag->linkTo("about", "About"); ?>
      </li>
      <li class="divider"></li>
      <li class="has-form"><a href="/docs" class="small button">Getting Started</a></li>
    </ul>
  </section>
</nav> 
