<section class="stage">
  <div class="row">
    <div class="medium-7 large-6 columns">
      <h1>Welcome to Phalconium</h1><br>
      <h3>Another spacy microsite application <br class="hide-for-small">based on Phalcon PHP Framework.</h3>
      <br>
    </div>
  </div>
  <div class="row">
    <div class="large-4 medium-6 columns">
      <?php print $this->tag->linkTo(array('docs', "Getting Started", 'class' => 'large button hide-for-small')); ?>
      <?php print $this->tag->linkTo(array('docs', "Getting Started", 'class' => 'small button show-for-small')); ?>
    </div>
  </div>
  <div class="floatingyeti">
    <?php print $this->tag->image("http://foundation.zurb.com/assets/img/homepage/hero-image.svg", false); ?>
  </div>
</section>
