<?php print $this->partial('partials/stage'); ?>

<section id="main-content">
  <div class="row">
    <div class="large-8 columns">
      <!--<h1><?php print $title; ?></h1>-->
      <p><strong>What is Phalcon?</strong> Phalcon is an open source, full stack framework for PHP written as a C-extension, optimized for high performance. You don’t need to learn or use the C language, since the functionality is exposed as PHP classes ready for you to use. Phalcon also is loosely coupled, allowing you to use its objects as glue components based on the needs of your application.</p>
      <p><strong>What is Foundation?</strong> Millions of designers and engineers use Foundation as part of their workflows. It was the first framework to introduce the concepts of responsive design, semantics, mobile first and partials. It's also compatibile with most browsers and devices. Foundation is the professional choice for designers and engineers.</p>
    </div>
    <div class="large-4 columns">
<!--      <h1><?php print $title; ?></h1>-->
      <p><strong>What is Phalcon?</strong> Phalcon is an open source, full stack framework for PHP written as a C-extension, optimized for high performance. You don’t need to learn or use the C language, since the functionality is exposed as PHP classes ready for you to use. Phalcon also is loosely coupled, allowing you to use its objects as glue components based on the needs of your application.</p>
    </div>
  </div>
</section>