<?php print $this->partial('partials/stage'); ?>

<?php print $this->partial('partials/intro'); ?>

<section class="main">
  <div class="row">
    <div class="large-8 columns">
      
      <?php echo $content->post ?>

    </div>
    <div class="large-4 columns">
      <p><strong>So what is Phalconium?</strong> Phalconium is a skeleton application based on Phalcon PHP and ZURB Foundation. It comes along with a very strong feature set:</p> 
      <ul>
        <li>Support for MySQL, Postgres and SQLite</li>
        <li>Responsive design with mobile first approach</li>
        <li>Pretty error interface for debugging issues</li>
        <li>Web tool for controller, models, scaffold and migrations</li>
      </ul>
    </div>
  </div>
</section>