<?php print $this->partial('partials/stage'); ?>

<section id="main-content">
  <div class="row">
    <div class="large-12 columns">
      <!--<h1><?php print $title; ?></h1>-->
      <p>Phalcon is an open source, full stack framework for PHP written as a C-extension, optimized for high performance. You don’t need to learn or use the C language, since the functionality is exposed as PHP classes ready for you to use. Phalcon also is loosely coupled, allowing you to use its objects as glue components based on the needs of your application.</p>
    </div>
  </div>
</section>