<section id="main-content">
  <div class="row">
    <div class="large-12 columns">
      <div>
        <h1>Getting Started</h1>

        <p>Phalcon is a PHP framework which is not written in PHP. It's an extension for PHP written in C. That means, you have to install it, before you can run it. In the <a href="http://docs.phalconphp.com/en/latest/reference/install.html" title="Phalcon Documentation">Phalcon Documentation</a> you can read how to do that.</p>

        <h2>Requirements</h2>
        <p>At least you need the following to run Phalconium on your machine:</p>

        <pre>apt-get install apache2 php5 php5-sqlite
a2enmod rewrite
service apache2 restart</pre>

        <h2>Installation</h2>
        <p>To clone Phalconium to your local webserver you can simply run:</p>

        <pre>cd /var/www/
git clone https://github.com/typomedia/phalconium.git
chown -R www-data:www-data phalconium/</pre>

        <p>Open <code>/app/config/config.php</code> and set the <code>baseUri</code> to <code>/phalconium/</code> if you have not set the DocumentRoot to <code>phalconium/public</code>.</p>

      </div>
    </div>
  </div>
</section>
