<section class="main">
  <div class="row">
    <div class="large-12 columns">
      <h1>Phalcon PHP Framework</h1>
      <p>Phalcon is an open source, full stack framework for PHP written as a C-extension, optimized for high performance. You don’t need to learn or use the C language, since the functionality is exposed as PHP classes ready for you to use. Phalcon also is loosely coupled, allowing you to use its objects as glue components based on the needs of your application.</p>
      <p>Phalcon is not only about performance, our goal is to make it robust, rich in features and easy to use!</p>
      <ul>
        <li>C-extensions are loaded together with PHP one time on the web server’s daemon start process</li>
        <li>Classes and functions provided by the extension are ready to use for any application</li>
        <li>The code is compiled and isn’t interpreted because is already compiled to a specific platform and processor</li>
        <li>Thanks to its low-level architecture and optimizations Phalcon provides the lowest overhead for MVC-based applications</li>
      </ul>
    </div>
  </div>
</section>