
<?php echo $this->getContent() ?>

<div class="right">
    <?php echo $this->tag->linkTo(array("posts/new", "Create posts")) ?>
</div>

<?php echo $this->tag->form(array("posts/search", "autocomplete" => "off")) ?>

<div class="center">
    <h1>Search posts</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="id">Id</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="name">Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="post">Post</label>
        </td>
        <td align="left">
                <?php echo $this->tag->textArea(array("post", "cols" => 30, "rows" => 4)) ?>
        </td>
    </tr>

    <tr>
        <td></td>
        <td><?php echo $this->tag->submitButton(array('Search', 'class' => 'small button')) ?></td>
    </tr>
</table>

</form>
