<?php // use Phalcon\Tag;  ?>

<?php echo $this->getContent(); ?>

<table width="100%">
  <tr>
    <td class="left">
      <?php echo $this->tag->linkTo(array("posts/index", "Home")); ?>
    </td>
    <td class="right">
      <?php echo $this->tag->linkTo(array("posts/new", "Create")); ?>
    </td>
  </tr>
</table>

<table class="browse">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Post</th>
      <th colspan="2">Tools</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($page->items as $post) { ?>
      <tr>
        <td><?php echo $post->id ?></td>
        <td><?php echo $post->name ?></td>
        <td><?php echo $post->post ?></td>
        <td><?php echo $this->tag->linkTo(array("posts/edit/" . $post->id, "Edit")); ?></td>
        <td><?php echo $this->tag->linkTo(array("posts/delete/" . $post->id, "Delete")); ?></td>
      </tr>
    <?php } ?>
  </tbody>
  <tbody>
    <tr>
      <td colspan="2" align="right">
        <table align="center">
          <tr>
            <td><?php echo $this->tag->linkTo("posts/search", "First") ?></td>
            <td><?php echo $this->tag->linkTo("posts/search?page=" . $page->before, "Previous") ?></td>
            <td><?php echo $this->tag->linkTo("posts/search?page=" . $page->next, "Next") ?></td>
            <td><?php echo $this->tag->linkTo("posts/search?page=" . $page->last, "Last") ?></td>
            <td><?php echo $page->current, "/", $page->total_pages ?></td>
          </tr>
        </table>
      </td>
    </tr>
  </tbody>
</table>
