<?php // use Phalcon\Tag;  ?>

<?php echo $this->getContent(); ?>

<dl class="sub-nav">
    <dd class="left"><?php echo $this->tag->linkTo(array("posts/index", "Home")); ?></dd>
    <dd class="right"><?php echo $this->tag->linkTo(array("posts/new", "Create")); ?></dd>
</dl>

<table class="browse">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Post</th>
      <th colspan="2">Tools</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($page->items as $post) { ?>
      <tr>
        <td><?php echo $post->id ?></td>
        <td><?php echo $post->name ?></td>
        <td><?php echo $post->post ?></td>
        <td><?php echo $this->tag->linkTo(array("posts/edit/" . $post->id, "Edit")); ?></td>
        <td><?php echo $this->tag->linkTo(array("posts/delete/" . $post->id, "Delete")); ?></td>
      </tr>
    <?php } ?>
  </tbody>
  </table>
  <ul class="pagination">
      <li><?php echo $this->tag->linkTo("posts/search", "First") ?></li>
      <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->before, "Previous") ?></li>
      <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->next, "Next") ?></li>
      <li><?php echo $this->tag->linkTo("posts/search?page=" . $page->last, "Last") ?></li>
      <li><?php echo $page->current, "/", $page->total_pages ?></li>
  </ul>

