<!doctype html>
<html class="no-js" lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <?php print $this->tag->getTitle(); ?>
    <?php print $this->tag->stylesheetLink('css/foundation/foundation.css'); ?>
    <?php print $this->tag->stylesheetLink('css/foundation/foundation-icons.css'); ?>
    <?php print $this->tag->stylesheetLink('css/typography.css'); ?>
    <?php print $this->tag->stylesheetLink('css/phalconium.css'); ?>
    <?php print $this->tag->javascriptInclude('js/foundation/vendor/modernizr.js'); ?>
  </head>
  <body id="<?php print $this->dispatcher->getControllerName(); ?>">
    <div class="off-canvas-wrap" data-offcanvas="">
      <div class="inner-wrap">

        <?php print $this->partial('partials/header'); ?>

        <?php print $this->getContent(); ?>

        <?php print $this->partial('partials/footer'); ?>

      </div>
    </div>
  </body>
</html>
